### ISSUE TITLE
really interested in using this :) Have a small problem

### ISSUE THREAD

**Issue by davidaw80** [dommmel/jekyll-contentful#6]
Hi, 
I am trying to figure out what the contentful_id field does. I believe I am missing something to make this work. This is my index.html page. I have already configured contentful with an article content_type and am referencing that ID in the _config.yml  file along with my production and preview keys. I have 3 entries in there - but i believe the - contentful_id:"home" field is not what I want. I am not worried about localization. I tried to follow all the documentation provided on that and wasn't clear. 

![screen shot 2015-10-11 at 1 02 08 pm](https://cloud.githubusercontent.com/assets/5204870/10418139/543a9044-7018-11e5-9e8d-02202525fbca.png)

**Comment by dommmel** [comment]
the `contentful_id` as used in the [example repo](https://github.com/dommmel/jekyll-contentful-example) is for i18n. It is used to link the localized versions of the index page together. This makes the  `{% language_switcher %}` tag work on those index pages.
