### ISSUE TITLE
Accessing Embedded Entries

### ISSUE THREAD

**Issue by npateman** [dommmel/jekyll-contentful#7]
Hi there,

I have a content type that has entries embedded inside of it, anywhere from 1 and above.  How to I access these?  I'm having difficulty getting to the fields of the entries, For example if I do

{{ page.contentful_fields.references | first }}

This gives me a #, joining with commas gives me #, # (assuming I have 2 references.

if I convert to JSON, I see this,

..."references":["#Contentful::Entry:0x00000002bf70f0","#Contentful::Entry:0x00000002ee3480"]...

I want to be able to enumerate the entries and get their fields.  Many thanks.

**Comment by dommmel** [comment]
This plugin does not handle references at the moment. Sorry.
