### ISSUE TITLE
Reference Issue

### ISSUE THREAD

**Issue by mthines** [dommmel/jekyll-contentful#9]
Hi Dommmel,
thanks for the plugin!

All my pages urls/slugs are based on their title, so I've created dynamic linking with the "title | slugify" filter and it works most places. 
Though when I'm trying to use the references content field I get a slightly problem. I've tried to remove the slugify and it's not the one causing the problem. The problem seems to be with your plugin and the reference field. All the other content fields get outputtet with no problem if isolated.

This is the content fields setup.

```
Name:    Accordion
Fields:  title_1
         link_1
         body_1
```

**My markup looks like this:**

```
<div class="test">
  {{ page.contentful_fields.title_1 }}
  {{ page.contentful_fields.link_1 }} // Only this one causing problem
  {{ page.contentful_fields.body_1 }}
</div>
```

Do you have an idea on how I might can get the reference field to work so I get the referenced's title outputted?

**This is the error**

```
Liquid Exception: undefined method `to_liquid' for #<Contentful::Entry:0x007fbfece7fc58> in accordion/component-page/index.html ...error:
  Error: undefined method `to_liquid' for #<Contentful::Entry:
  Error: Run jekyll build --trace for more information.
```

**Thanks!**

**Comment by funkycrash** [comment]
Hello @dommmel,
thanks for this wonderful plugin. I'm having the same issue.
I'm trying to access the property of a referenced object from Contentful and I'm getting the same error as @mads-thines.

`Error:  undefined method `to_liquid' for #<Contentful::Entry:0x007f9fbb28eda0>`

Do you gave any idea how we can workaround this issue?
Thank you
